on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'

env:
  TEST_TAG: hollysaiqs/artipie:test

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: 21
          distribution: adopt
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-jdk-21-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-jdk-21-maven-
          runs-on: ubuntu-latest
      - name: install jars
        run: mvn -B install -DskipTests
      - name: dowload dependencies
        run: mvn -B dependency:copy-dependencies
        working-directory: artipie-main
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: hollysaiqs/artipie
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and export to Docker
        uses: docker/build-push-action@v5
        with:
          context: artipie-main
          load: true
          tags: ${{ env.TEST_TAG }}
      - name: Test
        run: |
          docker run --rm ${{ env.TEST_TAG }} -h
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: artipie-main
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
